image:
  file: .gitpod.Dockerfile
ports:
  - port: 5500
    visibility: public
vscode:
  extensions:
    - ritwickdey.liveserver
    - twxs.cmake
    - ms-vscode.cmake-tools
    - ms-azuretools.vscode-docker
    - cschlosser.doxdocgen
    - webfreak.debug
    - eamodio.gitlens
    - https://github.com/microsoft/vscode-cpptools/releases/download/1.7.0-insiders2/cpptools-linux.vsix
    - https://github.com/matepek/vscode-catch2-test-adapter/releases/download/v3.6.32/matepek-vscode-catch2-test-adapter-3.6.32.vsix
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - matepek.vscode-catch2-test-adapter
