
image:
  file: .gitpod.Dockerfile
ports:
  - port: 5500
    visibility: public
vscode:
  extensions:
    - ritwickdey.liveserver
    - twxs.cmake
    - ms-vscode.cmake-tools
    - ms-azuretools.vscode-docker
    - cschlosser.doxdocgen
    - webfreak.debug
    - eamodio.gitlens
