image:
  file: .gitpod.Dockerfile
ports:
  - port: 5500
    visibility: public
vscode:
  extensions:
    - ritwickdey.liveserver
    - twxs.cmake
    - ms-vscode.cmake-tools
    - ms-azuretools.vscode-docker
    - cschlosser.doxdocgen
    - webfreak.debug
    - eamodio.gitlens
    - https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools/1.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
    - https://matepek.gallery.vsassets.io/_apis/public/gallery/publisher/matepek/extension/vscode-catch2-test-adapter/3.6.32/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

